require('dotenv').config();
const mongoose = require('mongoose');
const Property = require('./models/Property');
const Lead = require('./models/Lead');

const MONGO_URI = process.env.MONGO_URI';

const properties = [
    // ===== HOUSES =====
    {
        title: 'Luxurious 4BHK Bungalow',
        description: 'Spacious independent bungalow in the heart of Vijay Nagar with premium fittings, landscaped garden, and a rooftop terrace. Perfect for families seeking elegance and comfort in Indore\'s most sought-after locality.',
        category: 'house',
        price: 15500000,
        priceLabel: '₹1.55 Cr',
        location: 'Vijay Nagar, Indore',
        locality: 'Vijay Nagar',
        area: 3200,
        bedrooms: 4,
        bathrooms: 4,
        floors: 2,
        parking: true,
        furnished: 'Semi-Furnished',
        amenities: ['Garden', 'Rooftop Terrace', 'Modular Kitchen', 'CCTV', 'Power Backup', 'Security Guard'],
        highlights: ['Corner Plot', 'Vastu Compliant', 'Prime Location', 'Wide Road Facing'],
        status: 'Available',
        facing: 'East',
        age: '2 Years',
        contactPerson: 'Rahul Sharma',
        contactPhone: '+91 98765 11001',
    },
    {
        title: 'Modern 3BHK Independent House',
        description: 'Well-planned 3BHK independent house in Scheme 54 near MB Hospital Road. Double height living area, kids play area, and solar panels installed.',
        category: 'house',
        price: 8500000,
        priceLabel: '₹85 Lakh',
        location: 'Scheme 54, Indore',
        locality: 'Scheme 54',
        area: 2100,
        bedrooms: 3,
        bathrooms: 3,
        floors: 2,
        parking: true,
        furnished: 'Unfurnished',
        amenities: ['Solar Panels', 'Modular Kitchen', 'Vastu Compliant', 'Power Backup', 'CCTV'],
        highlights: ['Near MB Hospital', 'Solar Energy', '30ft Road'],
        status: 'Available',
        facing: 'North',
        age: '1 Year',
        contactPerson: 'Priya Verma',
        contactPhone: '+91 98765 22002',
    },
    {
        title: 'Elegant 3BHK Kothi',
        description: 'Beautiful kothi in the upscale Palasia area, close to MG Road Mall and Treasure Island. Includes covered parking and servant quarters.',
        category: 'house',
        price: 12000000,
        priceLabel: '₹1.2 Cr',
        location: 'Palasia, Indore',
        locality: 'Palasia',
        area: 2800,
        bedrooms: 3,
        bathrooms: 3,
        floors: 2,
        parking: true,
        furnished: 'Fully Furnished',
        amenities: ['Servant Quarter', 'Covered Parking', 'Modular Kitchen', 'Security System', 'Garden'],
        highlights: ['Close to MG Road', 'Fully Furnished', 'Servant Quarter'],
        status: 'Under Negotiation',
        facing: 'West',
        age: '5 Years',
        contactPerson: 'Amit Joshi',
        contactPhone: '+91 98765 33003',
    },

    // ===== APARTMENTS =====
    {
        title: 'Premium 3BHK in Trilogee Complex',
        description: 'Luxury apartment in one of Indore\'s most prestigious gated communities near Super Corridor. World-class amenities including infinity pool, gym, and co-working space.',
        category: 'apartment',
        price: 9800000,
        priceLabel: '₹98 Lakh',
        location: 'Super Corridor, Indore',
        locality: 'Super Corridor',
        area: 1850,
        bedrooms: 3,
        bathrooms: 2,
        floors: 1,
        parking: true,
        furnished: 'Semi-Furnished',
        amenities: ['Infinity Pool', 'Gym', 'Co-Working Space', 'Clubhouse', 'Tennis Court', '24/7 Security', 'Landscaped Gardens'],
        highlights: ['Gated Community', 'IT Hub Proximity', 'Premium Complex'],
        status: 'Available',
        facing: 'East',
        age: 'New',
        contactPerson: 'Sneha Patel',
        contactPhone: '+91 98765 44004',
    },
    {
        title: '2BHK Ready to Move Apartment',
        description: 'Affordable and well-planned 2BHK in Annapurna Nagar with all basic amenities. Walking distance from markets and schools. Ready to move immediately.',
        category: 'apartment',
        price: 4200000,
        priceLabel: '₹42 Lakh',
        location: 'Annapurna Nagar, Indore',
        locality: 'Annapurna Nagar',
        area: 980,
        bedrooms: 2,
        bathrooms: 2,
        floors: 1,
        parking: true,
        furnished: 'Unfurnished',
        amenities: ['Lift', 'Power Backup', 'CCTV', 'Water Tank', 'Parking'],
        highlights: ['Ready to Move', 'Affordable', 'Central Location'],
        status: 'Available',
        facing: 'South',
        age: '3 Years',
        contactPerson: 'Deepak Agrawal',
        contactPhone: '+91 98765 55005',
    },
    {
        title: 'Skyline 4BHK Penthouse',
        description: 'Exclusive penthouse on the 18th floor with panoramic views of Indore city. Private terrace, jacuzzi, and premium Italian marble flooring throughout.',
        category: 'apartment',
        price: 25000000,
        priceLabel: '₹2.5 Cr',
        location: 'AB Road, Indore',
        locality: 'AB Road',
        area: 3600,
        bedrooms: 4,
        bathrooms: 4,
        floors: 1,
        parking: true,
        furnished: 'Fully Furnished',
        amenities: ['Private Terrace', 'Jacuzzi', 'Italian Marble', 'Smart Home System', 'Infinity Pool View', 'Concierge'],
        highlights: ['Penthouse', 'City View', 'Ultra Luxury', '18th Floor'],
        status: 'Available',
        facing: 'North-East',
        age: 'New',
        contactPerson: 'Ritu Malhotra',
        contactPhone: '+91 98765 66006',
    },
    {
        title: '1BHK Starter Apartment',
        description: 'Perfect starter home near Rajwada. Compact, modern 1BHK with all amenities. Great investment opportunity with high rental yields in Old Palasia area.',
        category: 'apartment',
        price: 2800000,
        priceLabel: '₹28 Lakh',
        location: 'Old Palasia, Indore',
        locality: 'Old Palasia',
        area: 620,
        bedrooms: 1,
        bathrooms: 1,
        floors: 1,
        parking: false,
        furnished: 'Semi-Furnished',
        amenities: ['Lift', 'CCTV', 'Power Backup', 'Intercom'],
        highlights: ['Near Rajwada', 'High Rental Yield', 'Investment Property'],
        status: 'Available',
        facing: 'East',
        age: '4 Years',
        contactPerson: 'Vikram Singh',
        contactPhone: '+91 98765 77007',
    },

    // ===== COMMERCIAL =====
    {
        title: 'Prime Showroom Space on MG Road',
        description: 'Ground floor commercial space with 40ft frontage on MG Road, Indore\'s busiest commercial corridor. Ideal for retail showroom, bank, or restaurant. High footfall location.',
        category: 'commercial',
        price: 35000000,
        priceLabel: '₹3.5 Cr',
        location: 'MG Road, Indore',
        locality: 'MG Road',
        area: 2800,
        bedrooms: 0,
        bathrooms: 2,
        floors: 1,
        parking: true,
        furnished: 'Unfurnished',
        amenities: ['40ft Frontage', 'Power Backup', 'Central AC', 'Loading Dock', 'CCTV', 'Separate Entrance'],
        highlights: ['Prime Commercial Location', 'High Footfall', 'Corner Property'],
        status: 'Available',
        facing: 'East',
        age: '10 Years',
        contactPerson: 'Manish Gupta',
        contactPhone: '+91 98765 88008',
    },
    {
        title: 'Premium Office Space - IT Park',
        description: 'Modern plug-and-play office space in Indore\'s booming IT Park near Super Corridor. Ideal for IT companies, startups, and BPO. Includes server room and conference facilities.',
        category: 'commercial',
        price: 18000000,
        priceLabel: '₹1.8 Cr',
        location: 'Rau Pithampur Road, Indore',
        locality: 'IT Park, Super Corridor',
        area: 4500,
        bedrooms: 0,
        bathrooms: 4,
        floors: 1,
        parking: true,
        furnished: 'Fully Furnished',
        amenities: ['Server Room', 'Conference Room', '10 Workstations', 'Cafeteria', 'Power Backup', 'Fibre Internet', 'Reception Area'],
        highlights: ['Plug & Play', 'IT Park', 'Near Airport'],
        status: 'Available',
        facing: 'North',
        age: '2 Years',
        contactPerson: 'Nikhil Soni',
        contactPhone: '+91 98765 99009',
    },
    {
        title: 'Warehouse & Storage Unit',
        description: 'Large warehouse facility near Sanwer Industrial Area with direct national highway access. Includes loading/unloading bays, security cabin, and 3-phase power supply.',
        category: 'commercial',
        price: 28000000,
        priceLabel: '₹2.8 Cr',
        location: 'Sanwer Road Industrial Area, Indore',
        locality: 'Sanwer Road',
        area: 12000,
        bedrooms: 0,
        bathrooms: 2,
        floors: 1,
        parking: true,
        furnished: 'Unfurnished',
        amenities: ['Loading/Unloading Bays', '3-Phase Power', 'Security Cabin', 'Covered Shed', 'Water Supply'],
        highlights: ['Highway Access', 'Industrial Zone', 'Large Storage'],
        status: 'Available',
        facing: 'North',
        age: '8 Years',
        contactPerson: 'Harish Bansal',
        contactPhone: '+91 98766 00010',
    },

    // ===== RENT =====
    {
        title: 'Fully Furnished 3BHK - Vijay Nagar',
        description: 'Luxuriously furnished 3BHK apartment available for rent in Vijay Nagar. All premium appliances included. Walking distance from C21 Mall, schools, and hospitals.',
        category: 'rent',
        price: 35000,
        priceLabel: '₹35K/mo',
        location: 'Vijay Nagar, Indore',
        locality: 'Vijay Nagar',
        area: 1600,
        bedrooms: 3,
        bathrooms: 2,
        floors: 1,
        parking: true,
        furnished: 'Fully Furnished',
        amenities: ['AC in All Rooms', 'Washing Machine', 'Refrigerator', 'Smart TV', 'Modular Kitchen', 'Lift', 'Power Backup'],
        highlights: ['Fully Furnished', 'Near C21 Mall', 'Premium Locality'],
        status: 'Available',
        facing: 'East',
        age: '3 Years',
        contactPerson: 'Swati Jain',
        contactPhone: '+91 98766 11011',
    },
    {
        title: 'Studio Apartment for Rent - AB Road',
        description: 'Compact studio apartment ideal for working professionals and students. Prime AB Road location with all utilities included. Metro station proximity is a huge plus.',
        category: 'rent',
        price: 12000,
        priceLabel: '₹12K/mo',
        location: 'AB Road, Indore',
        locality: 'AB Road',
        area: 480,
        bedrooms: 1,
        bathrooms: 1,
        floors: 1,
        parking: false,
        furnished: 'Fully Furnished',
        amenities: ['AC', 'Wi-Fi Ready', 'Washing Area', 'Intercom', 'CCTV'],
        highlights: ['Near Metro', 'Working Professionals', 'All Inclusive'],
        status: 'Available',
        facing: 'West',
        age: '2 Years',
        contactPerson: 'Raj Kumar',
        contactPhone: '+91 98766 22012',
    },
    {
        title: 'Commercial Space for Rent - Palasia',
        description: 'Ground + First floor commercial space available for rent on Palasia main road. Suitable for clinics, institutes, co-working spaces, or boutique stores.',
        category: 'rent',
        price: 55000,
        priceLabel: '₹55K/mo',
        location: 'Palasia Square, Indore',
        locality: 'Palasia',
        area: 2200,
        bedrooms: 0,
        bathrooms: 2,
        floors: 2,
        parking: true,
        furnished: 'Unfurnished',
        amenities: ['High Ceiling', 'Separate Entrance', 'Power Backup', 'CCTV', 'Parking for 8 Cars'],
        highlights: ['G+1 Floor', 'Main Road', 'High Visibility'],
        status: 'Available',
        facing: 'East',
        age: '12 Years',
        contactPerson: 'Suresh Yadav',
        contactPhone: '+91 98766 33013',
    },
];

const leads = [
    {
        name: 'Arjun Mehra',
        phone: '+91 94250 11111',
        email: 'arjun.mehra@gmail.com',
        interest: 'apartment',
        budget: '₹40L - ₹60L',
        budgetMin: 4000000,
        budgetMax: 6000000,
        preferredLocality: 'Vijay Nagar, Super Corridor',
        status: 'Site Visit',
        source: 'Website',
        assignedTo: 'Rahul Sharma',
        priority: 'High',
        lastContacted: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        followUpDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
        notes: [
            { text: 'Interested in 2BHK or 3BHK. Prefers east facing.', createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
            { text: 'Showed him Annapurna apt. Will visit Super Corridor project tomorrow.', createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
        ],
    },
    {
        name: 'Priya Singhania',
        phone: '+91 98760 22222',
        email: 'priya.singhania@outlook.com',
        interest: 'house',
        budget: '₹80L - ₹1.2Cr',
        budgetMin: 8000000,
        budgetMax: 12000000,
        preferredLocality: 'Scheme 54, Palasia',
        status: 'Negotiating',
        source: 'Referral',
        assignedTo: 'Priya Verma',
        priority: 'High',
        lastContacted: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
        followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
        notes: [
            { text: 'Looking for a 3BHK independent house. Has approved home loan of 90L.', createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) },
            { text: 'Visited Scheme 54 kothi. Liked it. Negotiating on price.', createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000) },
            { text: 'Offered 82L. Owner willing to settle at 85L.', createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
        ],
    },
    {
        name: 'Ravi Joshi',
        phone: '+91 97742 33333',
        email: 'ravi.j@yahoo.com',
        interest: 'commercial',
        budget: '₹1.5Cr - ₹3Cr',
        budgetMin: 15000000,
        budgetMax: 30000000,
        preferredLocality: 'MG Road, AB Road',
        status: 'Contacted',
        source: 'Phone',
        assignedTo: 'Amit Joshi',
        priority: 'Medium',
        lastContacted: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        followUpDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
        notes: [
            { text: 'Wants to open a restaurant chain outlet. Needs ground floor with 30ft+ frontage.', createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
            { text: 'Sent him details of MG Road showroom. Waiting for response.', createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000) },
        ],
    },
    {
        name: 'Kavita Sharma',
        phone: '+91 96301 44444',
        email: 'kavita.sharma85@gmail.com',
        interest: 'rent',
        budget: '₹20K - ₹40K/mo',
        budgetMin: 20000,
        budgetMax: 40000,
        preferredLocality: 'Vijay Nagar, New Palasia',
        status: 'New',
        source: 'Social Media',
        assignedTo: 'Unassigned',
        priority: 'Medium',
        lastContacted: null,
        notes: [
            { text: 'Relocating from Mumbai. Needs 3BHK furnished by June 2026.', createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
        ],
    },
    {
        name: 'Sunil Patel',
        phone: '+91 88261 55555',
        email: 'sunilpatel.ind@gmail.com',
        interest: 'apartment',
        budget: '₹90L - ₹1.5Cr',
        budgetMin: 9000000,
        budgetMax: 15000000,
        preferredLocality: 'Super Corridor, AB Road',
        status: 'Closed',
        source: 'Walk-in',
        assignedTo: 'Sneha Patel',
        priority: 'Low',
        lastContacted: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        notes: [
            { text: 'Looking for luxury apartment for investment.', createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000) },
            { text: 'Booked 3BHK in Trilogee Complex. Token amount paid.', createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) },
        ],
    },
    {
        name: 'Deepak Choubey',
        phone: '+91 75294 66666',
        email: '',
        interest: 'house',
        budget: '₹50L - ₹80L',
        budgetMin: 5000000,
        budgetMax: 8000000,
        preferredLocality: 'Scheme 54, Annapurna',
        status: 'Lost',
        source: 'Referral',
        assignedTo: 'Rahul Sharma',
        priority: 'Low',
        lastContacted: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        notes: [
            { text: 'Was looking for 2BHK house. Budget was too low for the area.', createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000) },
            { text: 'Went with a builder directly. Closed.', createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000) },
        ],
    },
    {
        name: 'Meghna Trivedi',
        phone: '+91 91823 77777',
        email: 'meghna.trivedi@hotmail.com',
        interest: 'any',
        budget: '₹1Cr - ₹2Cr',
        budgetMin: 10000000,
        budgetMax: 20000000,
        preferredLocality: 'Vijay Nagar, Palasia',
        status: 'Contacted',
        source: 'Website',
        assignedTo: 'Priya Verma',
        priority: 'High',
        lastContacted: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        notes: [
            { text: 'NRI investor. Looking for premium properties for rental income.', createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000) },
            { text: 'Interested in penthouse or independent bungalow. Will visit in 2 weeks.', createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
        ],
    },
];

async function seed() {
    try {
        await mongoose.connect(MONGO_URI);
        console.log('✅ Connected to MongoDB Atlas');

        // Clear existing data
        await Property.deleteMany({});
        await Lead.deleteMany({});
        console.log('🗑️  Cleared existing properties and leads');

        // Insert new data
        const insertedProps = await Property.insertMany(properties);
        const insertedLeads = await Lead.insertMany(leads);

        console.log(`✅ Seeded ${insertedProps.length} properties`);
        console.log(`✅ Seeded ${insertedLeads.length} leads`);
        console.log('\nCategories breakdown:');
        const cats = ['house', 'apartment', 'commercial', 'rent'];
        cats.forEach(c => {
            const count = properties.filter(p => p.category === c).length;
            console.log(`  ${c}: ${count} properties`);
        });
        console.log('\n🎉 Database seeded successfully!');
    } catch (err) {
        console.error('❌ Seed error:', err.message);
    } finally {
        await mongoose.disconnect();
        process.exit(0);
    }
}

seed();
