// ─── Types ────────────────────────────────────────────────────────────
export interface Agent {
  $id: string;
  name: string;
  email: string;
  avatar: string;
}

export interface Review {
  $id: string;
  name: string;
  avatar: string;
  review: string;
  rating: number;
  $createdAt: string;
}

export interface Gallery {
  $id: string;
  image: string;
}

export interface Property {
  $id: string;
  name: string;
  type: string;
  description: string;
  address: string;
  location: string;
  price: number;
  area: number;
  bedrooms: number;
  bathrooms: number;
  rating: number;
  facilities: string[];
  image: string;
  agent: Agent;
  reviews: Review[];
  gallery: Gallery[];
}

// ─── Image URLs (reused from the old seed data) ──────────────────────
export const galleryImages = [
  "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1638799869566-b17fa794c4de?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1560185009-dddeb820c7b7?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1641910532059-ad684fd3049c?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1621293954908-907159247fc8?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1604328702728-d26d2062c20b?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600435335786-d74d2bb6de37?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1635108198979-9806fdf275c6?q=60&w=640&auto=format&fit=crop",
];

export const agentImages = [
  "https://images.unsplash.com/photo-1691335053879-02096d6ee2ca?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1544723495-432537d12f6c?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1542507464418-09c375b86bbe?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1534308143481-c55f00be8bd7?q=60&w=640&auto=format&fit=crop",
];

export const reviewImages = [
  "https://images.unsplash.com/photo-1517331671191-ddc2c6d3ebd1?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1474176857210-7287d38d27c6?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1511551203524-9a24350a5771?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=60&w=640&auto=format&fit=crop",
];

export const propertiesImages = [
  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1605146768851-eda79da39897?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1561753757-d8880c5a3551?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1551241090-67de81d3541c?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1697299262049-e9b5fa1e9761?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1719299225324-301bad5c333c?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1582063289852-62e3ba2747f8?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1516095901529-0ef7be431a4f?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1600585153490-76fb20a32601?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1605276373954-0c4a0dac5b12?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=60&w=640&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1720432972486-2d53db5badf0?q=60&w=640&auto=format&fit=crop",
];

// ─── Hardcoded Agents ─────────────────────────────────────────────────
export const agents: Agent[] = [
  { $id: "agent-1", name: "Sarah Johnson", email: "sarah.johnson@restate.com", avatar: agentImages[0] },
  { $id: "agent-2", name: "Michael Chen", email: "michael.chen@restate.com", avatar: agentImages[1] },
  { $id: "agent-3", name: "David Williams", email: "david.williams@restate.com", avatar: agentImages[2] },
  { $id: "agent-4", name: "Emily Parker", email: "emily.parker@restate.com", avatar: agentImages[3] },
  { $id: "agent-5", name: "James Rodriguez", email: "james.rodriguez@restate.com", avatar: agentImages[4] },
];

// ─── Hardcoded Reviews ────────────────────────────────────────────────
export const reviews: Review[] = [
  { $id: "rev-1", name: "Olivia Martin", avatar: reviewImages[0], review: "Amazing property! The location is perfect and the views are breathtaking. Highly recommend.", rating: 5, $createdAt: "2025-12-15T10:30:00Z" },
  { $id: "rev-2", name: "Noah Thompson", avatar: reviewImages[1], review: "Great neighborhood and beautiful interior. The agent was very helpful throughout the process.", rating: 4, $createdAt: "2025-11-20T14:15:00Z" },
  { $id: "rev-3", name: "Emma Davis", avatar: reviewImages[2], review: "Spacious rooms and modern amenities. Perfect for a growing family. Loved it!", rating: 5, $createdAt: "2025-10-05T09:00:00Z" },
  { $id: "rev-4", name: "Liam Brown", avatar: reviewImages[3], review: "Good value for the price. Some minor maintenance needed but overall very satisfied.", rating: 3, $createdAt: "2025-09-18T16:45:00Z" },
  { $id: "rev-5", name: "Sophia Wilson", avatar: reviewImages[4], review: "Beautiful architecture and well-maintained gardens. A dream home indeed.", rating: 5, $createdAt: "2025-08-22T11:30:00Z" },
  { $id: "rev-6", name: "Lucas Garcia", avatar: reviewImages[0], review: "The open floor plan is fantastic. Natural light floods every room. Absolutely love it.", rating: 4, $createdAt: "2025-07-10T08:20:00Z" },
  { $id: "rev-7", name: "Ava Martinez", avatar: reviewImages[1], review: "Prime location with easy access to schools, parks, and shopping centers.", rating: 4, $createdAt: "2025-06-30T13:00:00Z" },
  { $id: "rev-8", name: "Ethan Anderson", avatar: reviewImages[2], review: "Modern kitchen and luxurious bathrooms. This property exceeded our expectations.", rating: 5, $createdAt: "2025-05-14T15:30:00Z" },
  { $id: "rev-9", name: "Mia Taylor", avatar: reviewImages[3], review: "Quiet neighborhood with friendly neighbors. Perfect retreat from the city.", rating: 4, $createdAt: "2025-04-20T10:00:00Z" },
  { $id: "rev-10", name: "Benjamin Lee", avatar: reviewImages[4], review: "Stunning sunset views from the balcony. Worth every penny.", rating: 5, $createdAt: "2025-03-08T17:45:00Z" },
];

// ─── Hardcoded Galleries ──────────────────────────────────────────────
export const galleries: Gallery[] = galleryImages.map((image, i) => ({
  $id: `gal-${i + 1}`,
  image,
}));

// ─── Hardcoded Properties ─────────────────────────────────────────────
export const properties: Property[] = [
  {
    $id: "prop-1",
    name: "Sunset Villa",
    type: "Villa",
    description: "A stunning villa with panoramic ocean views, featuring an infinity pool and lush tropical gardens. The open-concept living spaces are designed for seamless indoor-outdoor living.",
    address: "123 Ocean Drive, Malibu, CA 90265",
    location: "34.0259,-118.7798",
    price: 8500,
    area: 3200,
    bedrooms: 5,
    bathrooms: 4,
    rating: 5,
    facilities: ["Parking", "Wifi", "Gym", "Laundry", "Pet-friendly"],
    image: propertiesImages[0],
    agent: agents[0],
    reviews: [reviews[0], reviews[1], reviews[2], reviews[4], reviews[7]],
    gallery: [galleries[0], galleries[1], galleries[2], galleries[3]],
  },
  {
    $id: "prop-2",
    name: "Modern Loft",
    type: "Apartment",
    description: "A chic urban loft in the heart of downtown with exposed brick walls, floor-to-ceiling windows, and a rooftop terrace offering city skyline views.",
    address: "456 Main Street, New York, NY 10001",
    location: "40.7128,-74.0060",
    price: 4200,
    area: 1800,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4,
    facilities: ["Wifi", "Gym", "Laundry"],
    image: propertiesImages[1],
    agent: agents[1],
    reviews: [reviews[1], reviews[3], reviews[5], reviews[6], reviews[8]],
    gallery: [galleries[2], galleries[3], galleries[4]],
  },
  {
    $id: "prop-3",
    name: "Countryside Manor",
    type: "House",
    description: "A charming countryside estate with rolling hills, a private vineyard, and a beautifully restored farmhouse featuring rustic interiors.",
    address: "789 Vineyard Lane, Napa Valley, CA 94559",
    location: "38.2975,-122.2869",
    price: 6800,
    area: 4500,
    bedrooms: 4,
    bathrooms: 3,
    rating: 5,
    facilities: ["Parking", "Wifi", "Pet-friendly", "Publicpark"],
    image: propertiesImages[2],
    agent: agents[2],
    reviews: [reviews[0], reviews[2], reviews[4], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[4], galleries[5], galleries[6]],
  },
  {
    $id: "prop-4",
    name: "Harbor View Condo",
    type: "Condo",
    description: "Elegant waterfront condo with private marina access, gourmet kitchen, and floor-to-ceiling windows showcasing stunning harbor views.",
    address: "321 Harbor Blvd, San Diego, CA 92101",
    location: "32.7157,-117.1611",
    price: 3500,
    area: 1500,
    bedrooms: 3,
    bathrooms: 2,
    rating: 4,
    facilities: ["Parking", "Wifi", "Gym", "Laundry"],
    image: propertiesImages[3],
    agent: agents[3],
    reviews: [reviews[1], reviews[5], reviews[6], reviews[8], reviews[9]],
    gallery: [galleries[1], galleries[5], galleries[7]],
  },
  {
    $id: "prop-5",
    name: "Lakeside Retreat",
    type: "House",
    description: "A serene lakeside home surrounded by towering pines, featuring a private dock, hot tub, and wraparound deck perfect for entertaining.",
    address: "555 Lakeshore Dr, Lake Tahoe, CA 96150",
    location: "38.9399,-119.9772",
    price: 5200,
    area: 2800,
    bedrooms: 4,
    bathrooms: 3,
    rating: 5,
    facilities: ["Parking", "Wifi", "Pet-friendly"],
    image: propertiesImages[4],
    agent: agents[4],
    reviews: [reviews[0], reviews[3], reviews[5], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[2], galleries[6], galleries[8]],
  },
  {
    $id: "prop-6",
    name: "Urban Studio",
    type: "Studio",
    description: "A compact yet stylish studio apartment in the arts district with smart storage solutions, modern finishes, and vibrant neighborhood culture.",
    address: "88 Arts District Ave, Los Angeles, CA 90013",
    location: "34.0407,-118.2352",
    price: 1800,
    area: 650,
    bedrooms: 1,
    bathrooms: 1,
    rating: 3,
    facilities: ["Wifi", "Laundry"],
    image: propertiesImages[5],
    agent: agents[0],
    reviews: [reviews[2], reviews[4], reviews[6]],
    gallery: [galleries[3], galleries[7]],
  },
  {
    $id: "prop-7",
    name: "Mountain Chalet",
    type: "House",
    description: "A cozy mountain chalet with ski-in/ski-out access, stone fireplace, vaulted ceilings, and panoramic mountain views from every room.",
    address: "72 Alpine Way, Aspen, CO 81611",
    location: "39.1911,-106.8175",
    price: 7200,
    area: 3500,
    bedrooms: 5,
    bathrooms: 4,
    rating: 5,
    facilities: ["Parking", "Wifi", "Gym", "Ventilation", "Pet-friendly"],
    image: propertiesImages[6],
    agent: agents[1],
    reviews: [reviews[0], reviews[1], reviews[3], reviews[8], reviews[9]],
    gallery: [galleries[1], galleries[4], galleries[5], galleries[8]],
  },
  {
    $id: "prop-8",
    name: "Beachfront Bungalow",
    type: "House",
    description: "A laid-back beachfront bungalow with direct sand access, surf-inspired decor, and an outdoor shower surrounded by tropical plants.",
    address: "14 Surf Lane, Santa Cruz, CA 95060",
    location: "36.9741,-122.0308",
    price: 3900,
    area: 1600,
    bedrooms: 3,
    bathrooms: 2,
    rating: 4,
    facilities: ["Parking", "Wifi", "Pet-friendly"],
    image: propertiesImages[7],
    agent: agents[2],
    reviews: [reviews[2], reviews[5], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[6], galleries[7]],
  },
  {
    $id: "prop-9",
    name: "Penthouse Suite",
    type: "Apartment",
    description: "A luxurious penthouse with private elevator access, wrap-around terrace, chef's kitchen, and a dedicated home theater room.",
    address: "1 Skyline Tower, Miami, FL 33131",
    location: "25.7617,-80.1918",
    price: 9500,
    area: 4000,
    bedrooms: 4,
    bathrooms: 5,
    rating: 5,
    facilities: ["Parking", "Wifi", "Gym", "Laundry", "Ventilation"],
    image: propertiesImages[8],
    agent: agents[3],
    reviews: [reviews[0], reviews[1], reviews[4], reviews[7], reviews[8]],
    gallery: [galleries[2], galleries[3], galleries[5], galleries[8]],
  },
  {
    $id: "prop-10",
    name: "Garden Townhouse",
    type: "Townhouse",
    description: "An elegant three-story townhouse with a private courtyard garden, chef's kitchen, and a rooftop deck with city views.",
    address: "205 Garden Row, Boston, MA 02116",
    location: "42.3496,-71.0780",
    price: 4800,
    area: 2200,
    bedrooms: 3,
    bathrooms: 3,
    rating: 4,
    facilities: ["Parking", "Wifi", "Laundry", "Publicpark"],
    image: propertiesImages[9],
    agent: agents[4],
    reviews: [reviews[3], reviews[6], reviews[8], reviews[9]],
    gallery: [galleries[1], galleries[4], galleries[7]],
  },
  {
    $id: "prop-11",
    name: "Desert Oasis",
    type: "Villa",
    description: "An architectural masterpiece in the desert featuring a resort-style pool, outdoor kitchen, and expansive desert landscape views.",
    address: "900 Cactus Rd, Scottsdale, AZ 85251",
    location: "33.4942,-111.9261",
    price: 6200,
    area: 3800,
    bedrooms: 4,
    bathrooms: 4,
    rating: 4,
    facilities: ["Parking", "Wifi", "Gym", "Pet-friendly"],
    image: propertiesImages[10],
    agent: agents[0],
    reviews: [reviews[0], reviews[2], reviews[5], reviews[7]],
    gallery: [galleries[0], galleries[3], galleries[6], galleries[8]],
  },
  {
    $id: "prop-12",
    name: "City Center Duplex",
    type: "Duplex",
    description: "A modern duplex in the city center with separate living quarters, shared rooftop terrace, and walkability to top restaurants and shops.",
    address: "67 Central Ave, Chicago, IL 60601",
    location: "41.8781,-87.6298",
    price: 3200,
    area: 2000,
    bedrooms: 3,
    bathrooms: 2,
    rating: 4,
    facilities: ["Wifi", "Gym", "Laundry", "Ventilation"],
    image: propertiesImages[11],
    agent: agents[1],
    reviews: [reviews[1], reviews[4], reviews[6], reviews[9]],
    gallery: [galleries[2], galleries[5], galleries[7]],
  },
  {
    $id: "prop-13",
    name: "Riverside Cottage",
    type: "House",
    description: "A quaint riverside cottage with a wraparound porch, stone fireplace, and private access to a pristine river for kayaking and fishing.",
    address: "33 River Bend Rd, Portland, OR 97201",
    location: "45.5152,-122.6784",
    price: 2900,
    area: 1400,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4,
    facilities: ["Parking", "Wifi", "Pet-friendly", "Publicpark"],
    image: propertiesImages[12],
    agent: agents[2],
    reviews: [reviews[0], reviews[3], reviews[8]],
    gallery: [galleries[1], galleries[4], galleries[6]],
  },
  {
    $id: "prop-14",
    name: "Skyline Apartment",
    type: "Apartment",
    description: "A sleek high-rise apartment with floor-to-ceiling windows, concierge service, and access to a residents-only sky lounge.",
    address: "150 Tower Pl, Seattle, WA 98101",
    location: "47.6062,-122.3321",
    price: 3800,
    area: 1200,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4,
    facilities: ["Wifi", "Gym", "Laundry", "Ventilation"],
    image: propertiesImages[13],
    agent: agents[3],
    reviews: [reviews[2], reviews[5], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[3], galleries[8]],
  },
  {
    $id: "prop-15",
    name: "Colonial Estate",
    type: "House",
    description: "A stately colonial home with original hardwood floors, crown molding, a grand staircase, and a beautifully landscaped half-acre lot.",
    address: "412 Heritage Ln, Charleston, SC 29401",
    location: "32.7765,-79.9311",
    price: 5500,
    area: 3600,
    bedrooms: 5,
    bathrooms: 4,
    rating: 5,
    facilities: ["Parking", "Wifi", "Laundry", "Pet-friendly", "Publicpark"],
    image: propertiesImages[0],
    agent: agents[4],
    reviews: [reviews[1], reviews[4], reviews[6], reviews[8], reviews[9]],
    gallery: [galleries[2], galleries[5], galleries[7], galleries[8]],
  },
  {
    $id: "prop-16",
    name: "Tropical Villa",
    type: "Villa",
    description: "An exotic tropical villa with thatched roof pavilions, a private infinity pool, and lush gardens filled with exotic flowers.",
    address: "8 Palm Grove, Key West, FL 33040",
    location: "24.5551,-81.7800",
    price: 7800,
    area: 3400,
    bedrooms: 4,
    bathrooms: 3,
    rating: 5,
    facilities: ["Parking", "Wifi", "Gym", "Pet-friendly"],
    image: propertiesImages[1],
    agent: agents[0],
    reviews: [reviews[0], reviews[2], reviews[3], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[1], galleries[4], galleries[6]],
  },
  {
    $id: "prop-17",
    name: "Industrial Loft",
    type: "Studio",
    description: "A converted warehouse loft with soaring 16-foot ceilings, polished concrete floors, and a mezzanine bedroom overlooking the living space.",
    address: "220 Factory St, Brooklyn, NY 11201",
    location: "40.6892,-73.9857",
    price: 2500,
    area: 950,
    bedrooms: 1,
    bathrooms: 1,
    rating: 3,
    facilities: ["Wifi", "Laundry", "Ventilation"],
    image: propertiesImages[2],
    agent: agents[1],
    reviews: [reviews[1], reviews[6], reviews[8]],
    gallery: [galleries[3], galleries[5]],
  },
  {
    $id: "prop-18",
    name: "Hilltop Mansion",
    type: "House",
    description: "A grand hilltop mansion with a 360-degree view terrace, wine cellar, home gym, and a private driveway lined with mature oak trees.",
    address: "1 Hilltop Circle, Beverly Hills, CA 90210",
    location: "34.0736,-118.4004",
    price: 9800,
    area: 5500,
    bedrooms: 6,
    bathrooms: 5,
    rating: 5,
    facilities: ["Parking", "Wifi", "Gym", "Laundry", "Ventilation", "Pet-friendly"],
    image: propertiesImages[3],
    agent: agents[2],
    reviews: [reviews[0], reviews[1], reviews[2], reviews[4], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[2], galleries[4], galleries[6], galleries[8]],
  },
  {
    $id: "prop-19",
    name: "Cozy Townhome",
    type: "Townhouse",
    description: "A charming two-story townhome on a tree-lined street with an attached garage, modern kitchen, and a cozy backyard patio.",
    address: "58 Maple Court, Austin, TX 78701",
    location: "30.2672,-97.7431",
    price: 2800,
    area: 1700,
    bedrooms: 3,
    bathrooms: 2,
    rating: 4,
    facilities: ["Parking", "Wifi", "Laundry"],
    image: propertiesImages[4],
    agent: agents[3],
    reviews: [reviews[3], reviews[5], reviews[6], reviews[8]],
    gallery: [galleries[1], galleries[7], galleries[8]],
  },
  {
    $id: "prop-20",
    name: "Seaside Condo",
    type: "Condo",
    description: "A bright and airy beachside condo with a wrap-around balcony, ocean breezes, community pool, and steps to the sandy shore.",
    address: "30 Shoreline Way, Honolulu, HI 96815",
    location: "21.2770,-157.8168",
    price: 4500,
    area: 1300,
    bedrooms: 2,
    bathrooms: 2,
    rating: 4,
    facilities: ["Wifi", "Gym", "Laundry", "Parking"],
    image: propertiesImages[5],
    agent: agents[4],
    reviews: [reviews[0], reviews[2], reviews[5], reviews[7], reviews[9]],
    gallery: [galleries[0], galleries[3], galleries[5], galleries[8]],
  },
];